=begin
#Fax.to REST API client for Ruby

#This is Fax.to REST API client for Ruby.

OpenAPI spec version: 2.0.0
Contact: inquiries@fax.to
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FaxSendingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FaxSendingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FaxSendingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FaxSendingApi' do
    it 'should create an instance of FaxSendingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FaxSendingApi)
    end
  end

  # unit tests for fax_document_id_costs_get
  # This API is for computing the cost of the fax to be sent
  # @param document_id The id of the document to be sent
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fax_number The fax number of the recipient
  # @return [InlineResponse2001]
  describe 'fax_document_id_costs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_history_get
  # This API gets the history of a fax
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit The number of record to return
  # @option opts [String] :page The page you want to get
  # @return [InlineResponse2003]
  describe 'fax_history_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_job_id_status_get
  # This API gets the status of a fax
  # @param fax_job_id The id of the fax job
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'fax_job_id_status_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_post
  # This API is for sending a new fax in any fax numbers anywhere in the world
  # @param fax_number The fax number of the recipient
  # @param document_id The id of the document to be sent
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'fax_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_clean_get
  # This API is used for cleaning a document
  # @param document_id The id of the document
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2009]
  describe 'file_clean_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_generate_preview_get
  # This API generates a preview of a document
  # @param document_id The id of the document
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20010]
  describe 'file_generate_preview_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_document_id_delete
  # This API deletes a document
  # @param document_id The id of the document
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20011]
  describe 'files_document_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_get
  # This API gets all the files of a certain user
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit The number of record to return
  # @option opts [String] :page The page you want to get
  # @return [InlineResponse2008]
  describe 'files_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
