=begin
#Fax.to REST API client for Ruby

#This is Fax.to REST API client for Ruby.

OpenAPI spec version: 2.0.0
Contact: inquiries@fax.to
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_10'
require 'swagger_client/models/inline_response_200_11'
require 'swagger_client/models/inline_response_200_12'
require 'swagger_client/models/inline_response_200_12_data'
require 'swagger_client/models/inline_response_200_13'
require 'swagger_client/models/inline_response_200_13_states'
require 'swagger_client/models/inline_response_200_14'
require 'swagger_client/models/inline_response_200_14_areacodes'
require 'swagger_client/models/inline_response_200_15'
require 'swagger_client/models/inline_response_200_15_data'
require 'swagger_client/models/inline_response_200_16'
require 'swagger_client/models/inline_response_200_16_data'
require 'swagger_client/models/inline_response_200_17'
require 'swagger_client/models/inline_response_200_17_numbers'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_3_created'
require 'swagger_client/models/inline_response_200_3_history'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_4_inbox'
require 'swagger_client/models/inline_response_200_4_meta'
require 'swagger_client/models/inline_response_200_4_meta_pagination'
require 'swagger_client/models/inline_response_200_4_meta_pagination_links'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_200_7'
require 'swagger_client/models/inline_response_200_8'
require 'swagger_client/models/inline_response_200_8_files'
require 'swagger_client/models/inline_response_200_9'
require 'swagger_client/models/inline_response_400'

# APIs
require 'swagger_client/api/fax_receiving_api'
require 'swagger_client/api/fax_sending_api'
require 'swagger_client/api/user_api'
require 'swagger_client/api/user_management_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
